import type { Apartment, Region } from "./types";

export const apartments: Apartment[] = [
  {
    id: "seongsu-riverview",
    name: "성수 리버뷰 아파트",
    city: "서울",
    district: "성동구",
    dong: "성수동",
    address: "서울 성동구 성수동1가 685",
    builtYear: 2019,
    households: 450,
    areaPy: 25,
    avgPrice: 7.8,
    priceMin: 7.2,
    priceMax: 8.4,
    dealTypes: ["매매", "전세"],
    jeonsePrice: 5.4,
    recentChangeRate: 2.1,
    elementarySchoolWalkMin: 8,
    subwayWalkMin: 5,
    subwayLine: "2호선 성수역",
    commuteMinutes: 18,
    moveInDate: "즉시입주",
    transitScore: 5,
    infraScore: 4,
    infraFacilities: [
      "서울숲 도보 7분",
      "이마트 성수점 도보 10분",
      "성수동 카페거리 및 상권 도보 5분",
    ],
    tags: ["역세권", "한강뷰", "신축급"],
    pros: [
      "성수역까지 도보 5분으로 2호선 이용이 매우 편리합니다.",
      "서울숲과 한강 접근성이 좋아 주거 만족도가 높습니다.",
      "최근 3개월 실거래가가 꾸준히 상승 중입니다.",
    ],
    considerations: [
      "평균 시세가 인근 대비 다소 높은 편입니다.",
      "초등학교까지 도보 8분으로 저학년 통학 시 보호자 동행이 권장됩니다.",
    ],
    priceHistory: [
      { yearMonth: "2024-07", price: 7.1 },
      { yearMonth: "2024-09", price: 7.3 },
      { yearMonth: "2024-11", price: 7.4 },
      { yearMonth: "2025-01", price: 7.5 },
      { yearMonth: "2025-03", price: 7.6 },
      { yearMonth: "2025-05", price: 7.7 },
      { yearMonth: "2026-01", price: 7.8 },
    ],
    nearbyApartmentIds: ["mapo-newlywed-village"],
    lat: 37.5446,
    lng: 127.0557,
  },
  {
    id: "gangdong-centralpark",
    name: "강동 센트럴파크",
    city: "서울",
    district: "강동구",
    dong: "천호동",
    address: "서울 강동구 천호동 145-2",
    builtYear: 2016,
    households: 620,
    areaPy: 34,
    avgPrice: 6.9,
    priceMin: 6.4,
    priceMax: 7.3,
    dealTypes: ["매매", "전세"],
    jeonsePrice: 4.6,
    recentChangeRate: 1.2,
    elementarySchoolWalkMin: 10,
    subwayWalkMin: 12,
    subwayLine: "5호선 천호역",
    commuteMinutes: 28,
    moveInDate: "2026-09",
    transitScore: 3,
    infraScore: 4,
    infraFacilities: [
      "천호역 로데오거리 도보 8분",
      "현대백화점 천호점 도보 12분",
      "천호공원 도보 6분",
    ],
    tags: ["대단지", "학군 양호"],
    pros: [
      "620세대 대단지로 관리비 효율과 커뮤니티 시설이 우수합니다.",
      "천호역 상권이 가까워 생활 인프라가 편리합니다.",
    ],
    considerations: [
      "지하철역까지 도보 12분으로 역세권 대비 다소 거리감이 있습니다.",
      "송파구 인접 단지 대비 가격 상승폭이 완만한 편입니다.",
    ],
    priceHistory: [
      { yearMonth: "2024-07", price: 6.6 },
      { yearMonth: "2024-09", price: 6.65 },
      { yearMonth: "2024-11", price: 6.7 },
      { yearMonth: "2025-01", price: 6.75 },
      { yearMonth: "2025-03", price: 6.8 },
      { yearMonth: "2025-05", price: 6.85 },
      { yearMonth: "2026-01", price: 6.9 },
    ],
    nearbyApartmentIds: ["songpa-parkview"],
    lat: 37.5382,
    lng: 127.1237,
  },
  {
    id: "songpa-parkview",
    name: "송파 파크뷰",
    city: "서울",
    district: "송파구",
    dong: "잠실동",
    address: "서울 송파구 잠실동 27-8",
    builtYear: 2015,
    households: 980,
    areaPy: 34,
    avgPrice: 11.2,
    priceMin: 10.5,
    priceMax: 12.1,
    dealTypes: ["매매", "전세"],
    jeonsePrice: 7.8,
    recentChangeRate: 3.4,
    elementarySchoolWalkMin: 7,
    subwayWalkMin: 6,
    subwayLine: "2호선 잠실역",
    commuteMinutes: 14,
    moveInDate: "즉시입주",
    transitScore: 5,
    infraScore: 5,
    infraFacilities: [
      "롯데월드몰·롯데월드타워 도보 8분",
      "잠실한강공원 도보 10분",
      "잠실초·중·고 학군 도보 7분 이내",
    ],
    tags: ["대단지", "학군 우수", "역세권"],
    pros: [
      "잠실역 더블 역세권으로 서울 전역 이동이 편리합니다.",
      "롯데월드몰 등 대형 상업시설이 도보권입니다.",
      "학군 수요가 꾸준해 가격 방어력이 높습니다.",
    ],
    considerations: [
      "서울 내 상위권 시세로 초기 자금 부담이 큽니다.",
      "최근 3개월 상승폭이 커 매수 타이밍 고려가 필요합니다.",
    ],
    priceHistory: [
      { yearMonth: "2024-07", price: 10.2 },
      { yearMonth: "2024-09", price: 10.5 },
      { yearMonth: "2024-11", price: 10.7 },
      { yearMonth: "2025-01", price: 10.9 },
      { yearMonth: "2025-03", price: 11.0 },
      { yearMonth: "2025-05", price: 11.0 },
      { yearMonth: "2026-01", price: 11.2 },
    ],
    nearbyApartmentIds: ["gangdong-centralpark"],
    lat: 37.5133,
    lng: 127.1001,
  },
  {
    id: "mapo-newlywed-village",
    name: "마포 신혼마을",
    city: "서울",
    district: "마포구",
    dong: "아현동",
    address: "서울 마포구 아현동 253-1",
    builtYear: 2020,
    households: 340,
    areaPy: 25,
    avgPrice: 6.5,
    priceMin: 6.0,
    priceMax: 6.9,
    dealTypes: ["매매", "전세", "월세"],
    jeonsePrice: 4.2,
    recentChangeRate: 1.8,
    elementarySchoolWalkMin: 6,
    subwayWalkMin: 4,
    subwayLine: "2호선 아현역",
    commuteMinutes: 15,
    moveInDate: "즉시입주",
    transitScore: 4,
    infraScore: 4,
    infraFacilities: [
      "마포 애플하우스·상권 도보 6분",
      "북아현 근린공원 도보 5분",
      "홈플러스 아현점 도보 9분",
    ],
    tags: ["신혼부부 추천", "신축", "역세권"],
    pros: [
      "신축 단지로 신혼부부 수요가 꾸준하고 소형 평형 위주로 구성되어 있습니다.",
      "아현역 도보 4분, 여의도·광화문 업무지구 접근성이 좋습니다.",
      "초등학교까지 도보 6분으로 향후 자녀 계획에도 무리가 없습니다.",
    ],
    considerations: [
      "세대수가 340세대로 대단지 대비 커뮤니티 시설이 제한적입니다.",
    ],
    priceHistory: [
      { yearMonth: "2024-07", price: 6.1 },
      { yearMonth: "2024-09", price: 6.2 },
      { yearMonth: "2024-11", price: 6.25 },
      { yearMonth: "2025-01", price: 6.3 },
      { yearMonth: "2025-03", price: 6.35 },
      { yearMonth: "2025-05", price: 6.4 },
      { yearMonth: "2026-01", price: 6.5 },
    ],
    nearbyApartmentIds: ["seongsu-riverview"],
    lat: 37.5577,
    lng: 126.9558,
  },
  {
    id: "singil-parkxi",
    name: "신길 파크자이",
    city: "서울",
    district: "영등포구",
    dong: "신길동",
    address: "서울 영등포구 신길동 4423",
    builtYear: 2018,
    households: 810,
    areaPy: 30,
    avgPrice: 6.8,
    priceMin: 6.3,
    priceMax: 7.2,
    dealTypes: ["매매", "전세"],
    jeonsePrice: 3.9,
    recentChangeRate: 0.9,
    elementarySchoolWalkMin: 12,
    subwayWalkMin: 9,
    subwayLine: "1호선 신길역",
    commuteMinutes: 17,
    moveInDate: "2026-11",
    transitScore: 3,
    infraScore: 3,
    infraFacilities: [
      "신길역 상권 도보 9분",
      "여의도 한강공원 버스 10분",
      "신길뉴타운 근린생활시설 조성 중",
    ],
    tags: ["대단지", "가성비", "신혼부부 추천"],
    pros: [
      "동일 면적 대비 가격 경쟁력이 있는 단지입니다.",
      "여의도 업무지구까지 대중교통 15분 내 이동이 가능합니다.",
    ],
    considerations: [
      "초등학교까지 도보 12분으로 등하교 동선 확인이 필요합니다.",
      "생활 인프라는 조성 중으로 향후 개선 여지가 있습니다.",
    ],
    priceHistory: [
      { yearMonth: "2024-07", price: 6.6 },
      { yearMonth: "2024-09", price: 6.6 },
      { yearMonth: "2024-11", price: 6.65 },
      { yearMonth: "2025-01", price: 6.7 },
      { yearMonth: "2025-03", price: 6.7 },
      { yearMonth: "2025-05", price: 6.75 },
      { yearMonth: "2026-01", price: 6.8 },
    ],
    nearbyApartmentIds: ["sangye-skyview"],
    lat: 37.5116,
    lng: 126.9175,
  },
  {
    id: "sangye-skyview",
    name: "상계 스카이뷰",
    city: "서울",
    district: "노원구",
    dong: "상계동",
    address: "서울 노원구 상계동 719",
    builtYear: 2012,
    households: 1200,
    areaPy: 25,
    avgPrice: 4.9,
    priceMin: 4.5,
    priceMax: 5.3,
    dealTypes: ["매매", "전세", "월세"],
    jeonsePrice: 3.2,
    recentChangeRate: 0.6,
    elementarySchoolWalkMin: 5,
    subwayWalkMin: 8,
    subwayLine: "4호선 노원역",
    commuteMinutes: 40,
    moveInDate: "즉시입주",
    transitScore: 4,
    infraScore: 3,
    infraFacilities: [
      "노원역 상권 도보 10분",
      "수락산 근린공원 도보 8분",
      "노원 이마트 도보 11분",
    ],
    tags: ["가성비", "학군 양호", "신혼부부 추천"],
    pros: [
      "서울 내 최저가권 단지 중 하나로 자금 부담이 적습니다.",
      "초등학교까지 도보 5분으로 자녀 통학이 편리합니다.",
      "1,200세대 대단지로 커뮤니티 시설이 풍부합니다.",
    ],
    considerations: [
      "2012년 준공으로 신축 대비 노후도가 있습니다.",
      "가격 상승률이 다른 지역 대비 완만한 편입니다.",
    ],
    priceHistory: [
      { yearMonth: "2024-07", price: 4.7 },
      { yearMonth: "2024-09", price: 4.75 },
      { yearMonth: "2024-11", price: 4.78 },
      { yearMonth: "2025-01", price: 4.8 },
      { yearMonth: "2025-03", price: 4.85 },
      { yearMonth: "2025-05", price: 4.87 },
      { yearMonth: "2026-01", price: 4.9 },
    ],
    nearbyApartmentIds: ["singil-parkxi"],
    lat: 37.6608,
    lng: 127.0699,
  },
];

export const regions: Region[] = [
  {
    id: "seongdong-seongsu",
    name: "성동구 성수동",
    city: "서울",
    avgPrice: 7.8,
    recentChangeRate: 2.1,
    transitScore: 5,
    infraScore: 4,
    summary:
      "서울숲·한강 접근성과 2호선 역세권을 갖춘 인기 주거지로, 최근 3개월간 시세가 꾸준히 상승하고 있습니다.",
    tags: ["역세권", "한강뷰", "MZ세대 선호"],
    apartmentIds: ["seongsu-riverview"],
  },
  {
    id: "gangdong-cheonho",
    name: "강동구 천호동",
    city: "서울",
    avgPrice: 6.9,
    recentChangeRate: 1.2,
    transitScore: 3,
    infraScore: 4,
    summary:
      "대단지 위주로 구성된 실거주 중심 지역으로, 상권과 학군이 안정적이며 완만한 시세 상승세를 보입니다.",
    tags: ["대단지", "실거주 선호"],
    apartmentIds: ["gangdong-centralpark"],
  },
  {
    id: "songpa-jamsil",
    name: "송파구 잠실동",
    city: "서울",
    avgPrice: 11.2,
    recentChangeRate: 3.4,
    transitScore: 5,
    infraScore: 5,
    summary:
      "서울 내 대표적인 학군·상권 프리미엄 지역으로, 더블 역세권과 우수한 학군 수요로 가격 방어력이 높습니다.",
    tags: ["학군 우수", "역세권", "프리미엄"],
    apartmentIds: ["songpa-parkview"],
  },
  {
    id: "mapo-ahyeon",
    name: "마포구 아현동",
    city: "서울",
    avgPrice: 6.5,
    recentChangeRate: 1.8,
    transitScore: 4,
    infraScore: 4,
    summary:
      "신축 소형 평형 위주로 신혼부부 수요가 꾸준하며, 도심 업무지구 접근성이 뛰어난 지역입니다.",
    tags: ["신혼부부 추천", "신축", "역세권"],
    apartmentIds: ["mapo-newlywed-village"],
  },
  {
    id: "yeongdeungpo-singil",
    name: "영등포구 신길동",
    city: "서울",
    avgPrice: 6.8,
    recentChangeRate: 0.9,
    transitScore: 3,
    infraScore: 3,
    summary:
      "여의도 접근성 대비 가격 경쟁력이 있는 지역으로, 생활 인프라가 점차 개선되고 있습니다.",
    tags: ["가성비", "여의도 인접"],
    apartmentIds: ["singil-parkxi"],
  },
  {
    id: "nowon-sanggye",
    name: "노원구 상계동",
    city: "서울",
    avgPrice: 4.9,
    recentChangeRate: 0.6,
    transitScore: 4,
    infraScore: 3,
    summary:
      "서울 내 대표적인 실속형 주거지로, 초등학교 접근성이 좋고 자금 부담이 적어 첫 내 집 마련 수요가 많습니다.",
    tags: ["가성비", "학군 양호", "첫 내 집 추천"],
    apartmentIds: ["sangye-skyview"],
  },
];

export function getApartmentById(id: string): Apartment | undefined {
  return apartments.find((apt) => apt.id === id);
}

export function getRegionById(id: string): Region | undefined {
  return regions.find((region) => region.id === id);
}

export function getNearbyApartments(apartment: Apartment): Apartment[] {
  return apartment.nearbyApartmentIds
    .map((id) => getApartmentById(id))
    .filter((apt): apt is Apartment => Boolean(apt));
}
